mistral-medium:
  prompt_template: "mistral-medium/basic_chatml_prompt.txt" # together already deals with prompt
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "mistral-medium"
    max_tokens: 4096
    requires_chatml: True
    price_per_token: 8e-6
    client_kwargs:
      base_url: 'https://api.mistral.ai/v1'
  pretty_name: "Mistral Medium"
  link: "https://mistral.ai/news/la-plateforme/"
