internlm2-chat-20b-ppo:
  prompt_template: "internlm2-chat-20b-ppo/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "internlm/internlm2-chat-20b"
    model_kwargs:
      torch_dtype: "bfloat16"
      trust_remote_code: True
    is_fast_tokenizer: False
    max_new_tokens: 2048
    batch_size: 32
    eos_token_id: 92542
    remove_ending: "<|im_end|>"
  pretty_name: "InternLM2 Chat 20B"
  link: "https://huggingface.co/internlm/internlm2-chat-20b"
