Mistral-7B+RAHF-DUAL+LoRA:
  prompt_template: "Mistral-7B+RAHF-DUAL+LoRA/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "./Mistral-7B+RAHF-DUAL+LoRA" # local path
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    do_sample: False
    repetition_penalty: 1.2
  pretty_name: "Mistral-7B+RAHF-DUAL+LoRA"
  link: "https://huggingface.co/Liuwenhao2022/Mistral-7B-LoRA-RAHF-DUAL"