gpt-4-turbo-2024-04-09:
  prompt_template: "gpt4_1106_preview/chatml_prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-4-turbo-2024-04-09"
    max_tokens: 4096
  pretty_name: "GPT-4 Turbo (04/09)"