gpt-4-0125-preview:
  prompt_template: "gpt4_1106_preview/chatml_prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-4-0125-preview"
    max_tokens: 4096
  pretty_name: "GPT-4 Preview (01/25)"