chatglm2-6b:
  prompt_template: "chatglm2-6b/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "THUDM/chatglm2-6b"
    model_kwargs:
      torch_dtype: 'float16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "ChatGLM2-6B"
  link: "https://huggingface.co/THUDM/chatglm2-6b"
