guanaco-33b-api:
  prompt_template: "guanaco-7b/prompt.txt"
  fn_completions: "huggingface_api_completions"
  completions_kwargs:
    model_name: "timdettmers/guanaco-33b-merged"
    max_new_tokens: 256
    temperature: 0.7
    do_sample: True
    gpu: True