gemini-pro:
  prompt_template: "gemini-pro/prompt.txt"
  fn_completions: "google_completions"
  completions_kwargs:
    model_name: "gemini-pro"
    max_output_tokens: 2048
    candidate_count: 1
  pretty_name: "Gemini Pro"