yi-large-preview:
  prompt_template: "yi-large-preview/prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "yi-large-preview"
    requires_chatml: True
    temperature: 0.6
    num_procs: 20
    max_tokens: 4000
    top_p: 0.9
    client_kwargs:
      base_url: "http://api.01ww.xyz/v1"
  pretty_name: "Yi-Large Preview"