Conifer-7B-DPO:
  prompt_template: "Conifer-7B-DPO/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "Conifer-7B-DPO"
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 0.9
    do_sample: True
  pretty_name: "Conifer-7B-DPO"
  link: "https://github.com/ConiferLM/Conifer"
