oasst_pythia_12b:
  prompt_template: "oasst_pythia_12b/basic_prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5"
    max_new_tokens: 50
  completion_parser_kwargs:
    outputs_to_match:
      1: '(?:^|\n) ?Output \(a\)'
      2: '(?:^|\n) ?Output \(b\)'
  batch_size: 1
